### PR TITLE
feat: treat examples as integration tests

### PR DESCRIPTION
**Pull request by vbstreetz**
Signed-off-by: Mitchel Kelonye <vbstreetz@gmail.com>

### CODE REVIEW

**Comment by seanyoung** [comment]
@jsx did some refactoring which is causing merge conflicts, unfortunately. Please can you resolve the conflicts. Sorry about that!

**Comment by vbstreetz** [comment]
gotcha. on it..

**Comment by seanyoung** [comment]
> gotcha. on it..

Thanks!

**Comment by jordansexton** [comment]
Ah, I didn't see this, but this is done in https://github.com/solana-labs/solana-solidity.js/pull/7

**Comment by vbstreetz** [comment]
Gotcha. Closing this for now.

**Pull request closed without merging**
