### PR TITLE
solang now requires data account to the first account

### PR DESCRIPTION
**Pull request by seanyoung**
Signed-off-by: Sean Young <sean@mess.org>

### CODE REVIEW

**Comment by seanyoung** [comment]
https://github.com/hyperledger/solang/pull/1039

**Comment by LucasSte** [comment]
Why are you disabling some tests?
Have you run `yarn lint:fix` and `yarn fmt`?

**Comment by seanyoung** [comment]
> Why are you disabling some tests?

Events are no longer working with this library.

> Have you run `yarn lint:fix` and `yarn fmt`?

I've added them to the github workflow (`yarn lint` checks both)

**Review by LucasSte — APPROVED** [review]

**Comment by LucasSte** [comment]
> Events are no longer working with this library.

Should we fix this?

**Comment by seanyoung** [comment]
> Should we fix this?

I thought about that too. I thought I would have a look once your work is merged.

**Pull request merged**
